/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { WeaponDef, WeaponType, PlayerLoadout } from '../types/game';

export const WEAPON_DEFINITIONS: Record<WeaponType, WeaponDef> = {
  pistol: {
    id: 'pistol',
    name: 'Desert Eagle',
    category: 'secondary',
    damage: 32,
    fireRate: 4.5,
    magazineSize: 7,
    reserveAmmo: 42,
    reloadTime: 1.4,
    spread: 0.02,
    bulletSpeed: 70,
    range: 60,
    description: 'High caliber heavy sidearm with punchy stopping power.',
    modelColor: '#94a3b8',
    recoil: 0.15,
    twoHanded: false,
  },
  uzi: {
    id: 'uzi',
    name: 'Micro Uzi',
    category: 'secondary',
    damage: 16,
    fireRate: 13,
    magazineSize: 32,
    reserveAmmo: 128,
    reloadTime: 1.6,
    spread: 0.07,
    bulletSpeed: 65,
    range: 45,
    description: 'Blistering fire rate compact submachine gun for close quarters.',
    modelColor: '#334155',
    recoil: 0.09,
    twoHanded: false,
  },
  ak47: {
    id: 'ak47',
    name: 'AK-47',
    category: 'primary',
    damage: 28,
    fireRate: 8.5,
    magazineSize: 30,
    reserveAmmo: 120,
    reloadTime: 2.1,
    spread: 0.035,
    bulletSpeed: 80,
    range: 75,
    description: 'Rugged frontline battle rifle. High damage and steady bullet velocity.',
    modelColor: '#78350f',
    recoil: 0.18,
    twoHanded: true,
  },
  m4: {
    id: 'm4',
    name: 'M4 Tactical',
    category: 'primary',
    damage: 24,
    fireRate: 10.5,
    magazineSize: 30,
    reserveAmmo: 120,
    reloadTime: 1.8,
    spread: 0.022,
    bulletSpeed: 85,
    range: 80,
    description: 'High accuracy assault rifle with low recoil and crisp burst control.',
    modelColor: '#1e293b',
    recoil: 0.11,
    twoHanded: true,
  },
  shotgun: {
    id: 'shotgun',
    name: 'SPAS-12 Shotgun',
    category: 'primary',
    damage: 18, // per pellet
    pellets: 7,
    fireRate: 1.6,
    magazineSize: 8,
    reserveAmmo: 32,
    reloadTime: 2.4,
    spread: 0.095,
    bulletSpeed: 60,
    range: 35,
    description: 'Devastating pump-action shotgun. Lethal at point-blank range.',
    modelColor: '#475569',
    recoil: 0.35,
    twoHanded: true,
  },
  sniper: {
    id: 'sniper',
    name: 'Barrett .50 Cal',
    category: 'primary',
    damage: 90,
    fireRate: 1.1,
    magazineSize: 5,
    reserveAmmo: 20,
    reloadTime: 2.8,
    spread: 0.005,
    bulletSpeed: 120,
    range: 120,
    description: 'Heavy sniper rifle with laser guide and armor-piercing rounds.',
    modelColor: '#0f172a',
    recoil: 0.45,
    twoHanded: true,
  },
  rpg: {
    id: 'rpg',
    name: 'RPG-7 Rocket',
    category: 'primary',
    damage: 110,
    fireRate: 0.85,
    magazineSize: 1,
    reserveAmmo: 5,
    reloadTime: 2.9,
    spread: 0.015,
    bulletSpeed: 38,
    range: 90,
    isExplosive: true,
    blastRadius: 5.5,
    description: 'Fires high-explosive rockets with massive area of effect damage.',
    modelColor: '#365314',
    recoil: 0.5,
    twoHanded: true,
  },
  flamethrower: {
    id: 'flamethrower',
    name: 'Pyro Cannon',
    category: 'primary',
    damage: 12,
    fireRate: 20,
    magazineSize: 60,
    reserveAmmo: 180,
    reloadTime: 2.5,
    spread: 0.08,
    bulletSpeed: 35,
    range: 28,
    description: 'Projects continuous streams of blazing napalm that ignites enemies.',
    modelColor: '#c2410c',
    recoil: 0.05,
    twoHanded: true,
  },
};

export const DEFAULT_LOADOUT: PlayerLoadout = {
  primaryWeapon: 'ak47',
  secondaryWeapon: 'pistol',
  grenade: 'frag',
  perk: 'quick_refuel',
  headgear: 'beret_green',
  camo: 'woodland',
  callsign: 'SOLDIER',
  trailColor: '#f97316',
};

export const PERK_DEFINITIONS: Record<string, { name: string; description: string; stat: string }> = {
  afterburner: {
    name: 'Afterburner',
    description: '25% higher rocket thrust speed, slightly higher burn rate.',
    stat: '+25% Fly Speed',
  },
  high_capacity: {
    name: 'High Capacity Tank',
    description: 'Adds +50% extra Nitro fuel volume to your jetpack boots.',
    stat: '+50% Nitro Tank',
  },
  quick_refuel: {
    name: 'Rapid Turbocharge',
    description: 'Nitro recharges 60% faster when your boots hit ground or glide.',
    stat: '+60% Recharge',
  },
  heavy_armor: {
    name: 'Reinforced Kevlar',
    description: 'Increases maximum soldier health by +25 HP.',
    stat: '+25 Max Health',
  },
  scavenger: {
    name: 'Munitions Scavenger',
    description: 'Spawn with +2 extra grenades and +50% reserve ammo.',
    stat: '+2 Grenades & Ammo',
  },
};
